### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by jhack32**

### CODE REVIEW

**Comment by tinglycraniumplacidly** [comment]
:100:

**Comment by dijonkitchen** [comment]
@jhack32 : Please improve your Git commits in the future. See: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

**Comment by dijonkitchen** [comment]
Check indentations and semi-colons overall.

**Comment by aattsai** [comment]
:+1:

**Comment by dijonkitchen** [comment]
:+1:

**Comment by dijonkitchen** [comment]
@Yoonis mergeable when you're ready!

**Pull request merged**
