### PR TITLE
Add admin table and create association to restaurants/bars. Active wa…

### PR DESCRIPTION
**Pull request by jhack32**
…s added on Menu to bring previous menus back if necessary

### CODE REVIEW

**Comment by aattsai** [comment]
:+1:

**Comment by dijonkitchen** [comment]
Apologies if I missed this. So we decided Admins should be separate from Users? 

Would having a boolean value for admin rights work in the Users table?

**Comment by Yoonis** [comment]
__ :100: 
__ :thought_balloon:
:octocat:

**Comment by jhack32** [comment]
Yeah, having a boolean value in users table would work but the logic behind creating separate admin and users is because an admin should be required to give us more information when they signup and a get a separate view of the website. A business owner would want to keep their personal accounts and business account different, is what we were thinking.

**Comment by dijonkitchen** [comment]
:+1:

**Pull request merged**
