### PR TITLE
Re-add secrets.yml to repo. Add ENV variables for all configurations.

### PR DESCRIPTION
**Pull request by Yoonis**

### CODE REVIEW

**Comment by aattsai** [comment]
:+1:

**Comment by dijonkitchen** [comment]
As @Yoonis noted, this is the reference: http://stackoverflow.com/questions/23180650/how-to-solve-error-missing-secret-key-base-for-production-environment-on-h/26541742#26541742

**Comment by dijonkitchen** [comment]
:+1: 

This should work since our Config Vars are set on Heroku. Note that if you run this locally, you'll need to generate different keys for Dev or Test.

**Comment by dijonkitchen** [comment]
I'm thinking we might want to leave the generated secrets for Development and Test environments. Is there any danger in that? 

If we do so, people can easily clone the repo and work on it without setting up ENV variables.

**Pull request merged**
